### ISSUE TITLE
What to search in searchbar.

### ISSUE THREAD

**Issue by EMakadiya** [rdlopes/WebHere#4]
When I tried to serach anything it gives empty result. Can anyone tell me that how it works?

It give me below error.

Printing description of error:
Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x7f9c13f40900 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=http://www.google.com/search?q=appl, NSErrorFailingURLKey=http://www.google.com/search?q=appl, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}

**Comment by rdlopes** [comment]
Hi, as to understand the error, you have to read the exception and get the meaning of it, when it's possible (exceptions are sometime quite a pain to decipher).

Here, you're lucky, the exception says it all.

You tried to access http://www.google.com/search?q=appl
Meaning you typed "appl" in the search bar.

The search went to the network but the server or the network didn't send any reply within the timeout interval.

This means either that:
- you're not connected to the Internet.
- the site is down (Google, most unlikely)
- the timeout can be too restrictive for the speed of your internet.

**Comment by EMakadiya** [comment]
hi Rui,

now that error is disappear but when i tried to search anything it gives me 0 object as response.

can you please help me out?

**Comment by rdlopes** [comment]
I cannot help if I'm just left with a comment such as "now I get 0 results" ;-)

Do you have any errors?
Have you tried a debug session?

Envoyé de mon iPhone

**Comment by EMakadiya** [comment]
There is no error. When i am trying to search "apple" in search bar but i am not getting any response. So can you please tell me what i need to search so that i can see response in table.

**Comment by rdlopes** [comment]
Sorry for the time, have been busy.
You're right, configuration changed. I had to update Pods and change Google's query.
Here's the working version.

Thanks for having spotted this.
